<a href="https://colab.research.google.com/github/JordanBaker78/Data205_JordanBaker/blob/main/Capstone_Proj_extracode.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import plotly.graph_objects as go
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [2]:
stats_2023 = pd.read_csv('https://raw.githubusercontent.com/JordanBaker78/Data205_JordanBaker/refs/heads/main/Project_Datasets/Stats-2023.csv')
stats_2022 = pd.read_csv('https://raw.githubusercontent.com/JordanBaker78/Data205_JordanBaker/refs/heads/main/Project_Datasets/Stats-2022.csv')
stats_2021 = pd.read_csv('https://raw.githubusercontent.com/JordanBaker78/Data205_JordanBaker/refs/heads/main/Project_Datasets/Stats-2021.csv')
stats_2020 = pd.read_csv('https://raw.githubusercontent.com/JordanBaker78/Data205_JordanBaker/refs/heads/main/Project_Datasets/Stats-2020.csv')
stats_2019 = pd.read_csv('https://raw.githubusercontent.com/JordanBaker78/Data205_JordanBaker/refs/heads/main/Project_Datasets/Stats-2019.csv')

In [3]:
stats = pd.concat((stats_2023, stats_2022, stats_2021, stats_2020, stats_2019))
stats.tail()

,season,event_date,nano,market,name,alias,rush_att,rush_yds,rush_tds,pass_cmp,...,penalty_yds,first_downs,third_down_conv,third_down_att,third_down_conv_pct,fourth_down_conv,fourth_down_att,fourth_down_conv_pct,time_of_possession,boxscore_stats_link
529,2019,2020-01-19,oiGiwWPf0UqMC,Kansas City,Chiefs,KC,27,112,2,23,...,61,27,6,10,0.600,1,1,1.000,1790,https://www.pro-football-reference.com/boxscor...
530,2019,2020-01-19,D5QY6bOxfn8ZL,Green Bay,Packers,GB,16,62,1,31,...,46,21,3,9,0.333,2,2,1.000,1873,https://www.pro-football-reference.com/boxscor...
531,2019,2020-01-19,IwSI92ZDKoazn,San Francisco,49ers,SF,42,285,4,6,...,10,19,4,10,0.400,0,0,0.000,1727,https://www.pro-football-reference.com/boxscor...
532,2019,2020-02-02,IwSI92ZDKoazn,San Francisco,49ers,SF,22,141,1,20,...,45,21,3,8,0.375,0,1,0.000,1607,https://www.pro-football-reference.com/boxscor...
533,2019,2020-02-02,oiGiwWPf0UqMC,Kansas City,Chiefs,KC,29,129,2,26,...,24,26,6,14,0.429,2,3,0.667,1993,https://www.pro-football-reference.com/boxscor...

In [4]:
rush_avg = stats['rush_yds'] / stats['rush_att']
stats.insert(8, 'rush_avg', rush_avg)

In [5]:
rush_td_per_att = stats['rush_tds'] / stats['rush_att']
fumbles_lost_per_att = stats['fumbles_lost'] / stats['rush_att']
rush_success = stats['rush_avg'] + (4 * rush_td_per_att) - (4 * fumbles_lost_per_att)
stats.insert(9, 'rush_success', rush_success)

In [7]:
stats_2019 = stats[stats['season'] == 2019]
stats_2020 = stats[stats['season'] == 2020]
stats_2021 = stats[stats['season'] == 2021]
stats_2022 = stats[stats['season'] == 2022]
stats_2023 = stats[stats['season'] == 2023]
stats_2019.head()

,season,event_date,nano,market,name,alias,rush_att,rush_yds,rush_avg,rush_success,...,penalty_yds,first_downs,third_down_conv,third_down_att,third_down_conv_pct,fourth_down_conv,fourth_down_att,fourth_down_conv_pct,time_of_possession,boxscore_stats_link
0,2019,2019-09-05,D5QY6bOxfn8ZL,Green Bay,Packers,GB,22,47,2.136364,2.136364,...,71,13,2,12,0.167,0,0,0.0,1863,https://www.pro-football-reference.com/boxscor...
1,2019,2019-09-05,1vVmWGzUZ1rea,Chicago,Bears,CHI,15,46,3.066667,3.066667,...,107,16,3,15,0.200,0,2,0.0,1737,https://www.pro-football-reference.com/boxscor...
2,2019,2019-09-08,mLspw4gJNTQGN,Atlanta,Falcons,ATL,17,73,4.294118,4.058824,...,78,27,2,8,0.250,2,2,1.0,1813,https://www.pro-football-reference.com/boxscor...
3,2019,2019-09-08,AzOs5UWsXusSW,Minnesota,Vikings,MIN,38,172,4.526316,4.842105,...,100,18,5,10,0.500,0,0,0.0,1787,https://www.pro-football-reference.com/boxscor...
4,2019,2019-09-08,3VqeLK0LS9rpw,Buffalo,Bills,BUF,25,128,5.120000,4.960000,...,55,23,5,10,0.500,0,1,0.0,1679,https://www.pro-football-reference.com/boxscor...

In [8]:
rushing_2019 = stats_2019[['name', 'rush_att', 'rush_yds', 'rush_avg', 'rush_tds', 'rush_success', 'fumbles', 'fumbles_lost']]
rushing_2020 = stats_2020[['name', 'rush_att', 'rush_yds', 'rush_avg', 'rush_tds', 'rush_success', 'fumbles', 'fumbles_lost']]
rushing_2021 = stats_2021[['name', 'rush_att', 'rush_yds', 'rush_avg','rush_tds', 'rush_success', 'fumbles', 'fumbles_lost']]
rushing_2022 = stats_2022[['name', 'rush_att', 'rush_yds', 'rush_avg', 'rush_tds', 'rush_success', 'fumbles', 'fumbles_lost']]
rushing_2023 = stats_2023[['name', 'rush_att', 'rush_yds', 'rush_avg', 'rush_tds', 'rush_success', 'fumbles', 'fumbles_lost']]
rushing_total = stats[['season', 'name', 'rush_att', 'rush_yds', 'rush_avg', 'rush_tds', 'rush_success', 'fumbles', 'fumbles_lost']]
rushing_total.head()

,season,name,rush_att,rush_yds,rush_avg,rush_tds,rush_success,fumbles,fumbles_lost
0,2023,Ravens,16,81,5.062500,0,4.562500,2,2
1,2023,Chiefs,32,89,2.781250,1,2.906250,2,0
2,2023,49ers,33,155,4.696970,3,5.060606,0,0
3,2023,Lions,29,182,6.275862,3,6.551724,1,1
4,2023,Chiefs,24,146,6.083333,1,6.083333,2,1

In [9]:
all_teams_total_rush_2019 = stats_2019.groupby('name')['rush_yds'].sum().reset_index()
all_teams_total_rush_2020 = stats_2020.groupby('name')['rush_yds'].sum().reset_index()
all_teams_total_rush_2021 = stats_2021.groupby('name')['rush_yds'].sum().reset_index()
all_teams_total_rush_2022 = stats_2022.groupby('name')['rush_yds'].sum().reset_index()
all_teams_total_rush_2023 = stats_2023.groupby('name')['rush_yds'].sum().reset_index()

In [10]:
all_teams_rush_success_2019 = stats_2019.groupby('name')['rush_success'].mean().reset_index()
all_teams_rush_success_2020 = stats_2020.groupby('name')['rush_success'].mean().reset_index()
all_teams_rush_success_2021 = stats_2021.groupby('name')['rush_success'].mean().reset_index()
all_teams_rush_success_2022 = stats_2022.groupby('name')['rush_success'].mean().reset_index()
all_teams_rush_success_2023 = stats_2023.groupby('name')['rush_success'].mean().reset_index()

In [11]:
all_teams_rush_tds_2019 = stats_2019.groupby('name')['rush_tds'].sum().reset_index()
all_teams_rush_tds_2020 = stats_2020.groupby('name')['rush_tds'].sum().reset_index()
all_teams_rush_tds_2021 = stats_2021.groupby('name')['rush_tds'].sum().reset_index()
all_teams_rush_tds_2022 = stats_2022.groupby('name')['rush_tds'].sum().reset_index()
all_teams_rush_tds_2023 = stats_2023.groupby('name')['rush_tds'].sum().reset_index()

In [12]:
all_teams_rush_avg_2019 = stats_2019.groupby('name')['rush_avg'].mean().reset_index()
all_teams_rush_avg_2020 = stats_2020.groupby('name')['rush_avg'].mean().reset_index()
all_teams_rush_avg_2021 = stats_2021.groupby('name')['rush_avg'].mean().reset_index()
all_teams_rush_avg_2022 = stats_2022.groupby('name')['rush_avg'].mean().reset_index()
all_teams_rush_avg_2023 = stats_2023.groupby('name')['rush_avg'].mean().reset_index()

In [13]:
all_teams_rush_fumbles_lost_2019 = stats_2019.groupby('name')['fumbles_lost'].sum().reset_index()
all_teams_rush_fumbles_lost_2020 = stats_2020.groupby('name')['fumbles_lost'].sum().reset_index()
all_teams_rush_fumbles_lost_2021 = stats_2021.groupby('name')['fumbles_lost'].sum().reset_index()
all_teams_rush_fumbles_lost_2022 = stats_2022.groupby('name')['fumbles_lost'].sum().reset_index()
all_teams_rush_fumbles_lost_2023 = stats_2023.groupby('name')['fumbles_lost'].sum().reset_index()

In [18]:
total_rush_with_rank_19 = all_teams_total_rush_2019.copy()
total_rush_with_rank_19['rush_yds_rank'] = total_rush_with_rank_19['rush_yds'].rank(ascending=False, method='min')
rush_success_with_rank_19 = all_teams_rush_success_2019.copy()
rush_success_with_rank_19['rush_success_rank'] = rush_success_with_rank_19['rush_success'].rank(ascending=False, method='min')
rush_avg_with_rank_19 = all_teams_rush_avg_2019.copy()
rush_avg_with_rank_19['rush_avg_rank'] = rush_avg_with_rank_19['rush_avg'].rank(ascending=False, method='min')
rush_tds_with_rank_19 = all_teams_rush_tds_2019.copy()
rush_tds_with_rank_19['rush_tds_rank'] = rush_tds_with_rank_19['rush_tds'].rank(ascending=False, method='min')
rush_fumbles_lost_with_rank_19 = all_teams_rush_fumbles_lost_2019.copy()
rush_fumbles_lost_with_rank_19['fumbles_lost_rank'] = rush_fumbles_lost_with_rank_19['fumbles_lost'].rank(ascending=False, method='min')

In [22]:
rush_rank_19 = pd.merge(total_rush_with_rank_19[['name', 'rush_yds', 'rush_yds_rank']],
                          rush_avg_with_rank_19[['name', 'rush_avg', 'rush_avg_rank']],
                          on='name')
rush_rank_19 = pd.merge(rush_rank_19,
                          rush_tds_with_rank_19[['name', 'rush_tds', 'rush_tds_rank']],
                          on='name')
rush_rank_19 = pd.merge(rush_rank_19,
                          rush_fumbles_lost_with_rank_19[['name', 'fumbles_lost', 'fumbles_lost_rank']],
                          on='name')
rush_rank_19 = pd.merge(rush_rank_19,
                          rush_success_with_rank_19[['name', 'rush_success', 'rush_success_rank']],
                          on='name')
rush_rank_19.sort_values(by='rush_yds_rank')

,name,rush_yds,rush_yds_rank,rush_avg,rush_avg_rank,rush_tds,rush_tds_rank,fumbles_lost,fumbles_lost_rank,rush_success,rush_success_rank
25,Ravens,3481,1.0,5.591909,1.0,21,4.0,8,20.0,5.677782,1.0
0,49ers,2917,2.0,4.765868,4.0,30,1.0,11,8.0,4.890653,4.0
30,Titans,2726,3.0,4.903323,2.0,24,2.0,9,17.0,5.005486,2.0
27,Seahawks,2374,4.0,4.494113,12.0,18,10.0,14,3.0,4.521452,12.0
31,Vikings,2290,5.0,4.238566,19.0,21,4.0,14,3.0,4.236007,19.0
29,Texans,2244,6.0,4.594945,8.0,19,9.0,10,14.0,4.666341,7.0
3,Bills,2226,7.0,4.530394,10.0,13,18.0,8,20.0,4.560273,11.0
11,Cowboys,2153,8.0,4.570773,9.0,18,10.0,7,25.0,4.638386,8.0
10,Colts,2130,9.0,4.347141,14.0,17,14.0,11,8.0,4.390462,14.0
13,Eagles,2059,10.0,4.254327,17.0,16,15.0,15,2.0,4.239348,18.0
7,Cardinals,1990,11.0,4.710947,5.0,18,10.0,6,30.0,4.796604,5.0
20,Packers,1966,12.0,4.212736,20.0,21,4.0,10,14.0,4.308948,16.0
9,Chiefs,1928,13.0,4.335788,15.0,22,3.0,11,8.0,4.403217,13.0
5,Browns,1901,14.0,4.871105,3.0,15,16.0,7,25.0,4.931191,3.0
23,Raiders,1893,15.0,4.347785,13.0,13,18.0,9,17.0,4.374296,15.0
26,Saints,1835,16.0,4.495880,11.0,13,18.0,3,32.0,4.588693,9.0
21,Panthers,1819,17.0,4.650675,6.0,20,7.0,14,3.0,4.701115,6.0
22,Patriots,1801,18.0,3.864810,23.0,18,10.0,7,25.0,3.951842,23.0
17,Jaguars,1708,19.0,4.239507,18.0,3,32.0,12,7.0,4.124593,20.0
16,Giants,1685,20.0,4.648315,7.0,11,22.0,16,1.0,4.570246,10.0
4,Broncos,1662,21.0,4.079741,21.0,11,22.0,6,30.0,4.119730,21.0
19,Lions,1649,22.0,3.982290,22.0,7,29.0,8,20.0,3.984584,22.0
15,Football Team,1583,23.0,4.303562,16.0,9,26.0,8,20.0,4.299461,17.0
6,Buccaneers,1521,24.0,3.822256,24.0,15,16.0,11,8.0,3.854812,24.0
2,Bengals,1517,25.0,3.748939,26.0,9,26.0,14,3.0,3.670083,28.0
24,Rams,1499,26.0,3.601605,29.0,20,7.0,7,25.0,3.733692,26.0
1,Bears,1458,27.0,3.556264,30.0,8,28.0,7,25.0,3.522407,30.0
8,Chargers,1453,28.0,3.774626,25.0,12,21.0,11,8.0,3.761915,25.0
28,Steelers,1447,29.0,3.633715,28.0,7,29.0,11,8.0,3.589823,29.0
14,Falcons,1361,30.0,3.705976,27.0,10,24.0,10,14.0,3.681541,27.0
18,Jets,1257,31.0,3.302909,31.0,6,31.0,9,17.0,3.267099,31.0
12,Dolphins,1156,32.0,3.227848,32.0,10,24.0,8,20.0,3.243468,32.0

In [21]:
total_rush_with_rank_20 = all_teams_total_rush_2020.copy()
total_rush_with_rank_20['rush_yds_rank'] = total_rush_with_rank_20['rush_yds'].rank(ascending=False, method='min')
rush_success_with_rank_20 = all_teams_rush_success_2020.copy()
rush_success_with_rank_20['rush_success_rank'] = rush_success_with_rank_20['rush_success'].rank(ascending=False, method='min')
rush_avg_with_rank_20 = all_teams_rush_avg_2020.copy()
rush_avg_with_rank_20['rush_avg_rank'] = rush_avg_with_rank_20['rush_avg'].rank(ascending=False, method='min')
rush_tds_with_rank_20 = all_teams_rush_tds_2020.copy()
rush_tds_with_rank_20['rush_tds_rank'] = rush_tds_with_rank_20['rush_tds'].rank(ascending=False, method='min')
rush_fumbles_lost_with_rank_20 = all_teams_rush_fumbles_lost_2020.copy()
rush_fumbles_lost_with_rank_20['fumbles_lost_rank'] = rush_fumbles_lost_with_rank_20['fumbles_lost'].rank(ascending=False, method='min')

In [23]:
rush_rank_20 = pd.merge(total_rush_with_rank_20[['name', 'rush_yds', 'rush_yds_rank']],
                          rush_avg_with_rank_20[['name', 'rush_avg', 'rush_avg_rank']],
                          on='name')
rush_rank_20 = pd.merge(rush_rank_20,
                          rush_tds_with_rank_20[['name', 'rush_tds', 'rush_tds_rank']],
                          on='name')
rush_rank_20 = pd.merge(rush_rank_20,
                          rush_fumbles_lost_with_rank_20[['name', 'fumbles_lost', 'fumbles_lost_rank']],
                          on='name')
rush_rank_20 = pd.merge(rush_rank_20,
                          rush_success_with_rank_20[['name', 'rush_success', 'rush_success_rank']],
                          on='name')
rush_rank_20.sort_values(by='rush_yds_rank')

,name,rush_yds,rush_yds_rank,rush_avg,rush_avg_rank,rush_tds,rush_tds_rank,fumbles_lost,fumbles_lost_rank,rush_success,rush_success_rank
25,Ravens,3457,1.0,5.517918,1.0,26,2.0,7,20.0,5.634179,1.0
30,Titans,2741,2.0,4.956840,3.0,26,2.0,5,28.0,5.091006,3.0
5,Browns,2613,3.0,4.646493,8.0,24,4.0,9,13.0,4.740905,7.0
26,Saints,2492,4.0,4.505683,10.0,31,1.0,11,5.0,4.630851,10.0
20,Packers,2373,5.0,4.673548,6.0,18,15.0,7,20.0,4.735285,8.0
22,Patriots,2346,6.0,4.648017,7.0,20,8.0,5,28.0,4.755756,6.0
31,Vikings,2283,7.0,4.811172,5.0,20,8.0,10,11.0,4.903746,5.0
24,Rams,2278,8.0,4.273994,18.0,21,6.0,11,5.0,4.340139,18.0
7,Cardinals,2237,9.0,4.563360,9.0,22,5.0,8,17.0,4.670911,9.0
10,Colts,2159,10.0,4.407242,14.0,21,6.0,4,32.0,4.551314,11.0
9,Chiefs,2143,11.0,4.502418,11.0,16,18.0,10,11.0,4.541730,12.0
27,Seahawks,2107,12.0,4.864220,4.0,15,20.0,6,24.0,4.945417,4.0
13,Eagles,2027,13.0,5.117143,2.0,16,18.0,9,13.0,5.185485,2.0
6,Buccaneers,2009,14.0,3.968817,27.0,20,8.0,6,24.0,4.079416,24.0
3,Bills,1980,15.0,4.214148,19.0,17,16.0,11,5.0,4.265964,20.0
4,Broncos,1918,16.0,4.352109,15.0,13,23.0,9,13.0,4.389285,15.0
23,Raiders,1916,17.0,4.125884,21.0,20,8.0,16,1.0,4.092921,23.0
0,49ers,1889,18.0,4.345884,16.0,19,13.0,14,2.0,4.383331,16.0
11,Cowboys,1788,19.0,4.113185,23.0,14,22.0,13,3.0,4.117887,22.0
8,Chargers,1784,20.0,3.786357,30.0,12,28.0,6,24.0,3.822415,31.0
16,Giants,1768,21.0,4.427160,13.0,13,23.0,11,5.0,4.408768,14.0
21,Panthers,1704,22.0,4.195670,20.0,19,13.0,5,28.0,4.347869,17.0
15,Football Team,1697,23.0,3.956035,28.0,20,8.0,11,5.0,4.009059,27.0
1,Bears,1695,24.0,3.990102,25.0,12,28.0,6,24.0,4.022250,26.0
12,Dolphins,1688,25.0,3.885188,29.0,15,20.0,7,20.0,3.950485,29.0
18,Jets,1683,26.0,4.113598,22.0,9,31.0,5,28.0,4.153406,21.0
2,Bengals,1668,27.0,4.028330,24.0,13,23.0,13,3.0,3.985139,28.0
14,Falcons,1532,28.0,3.773405,31.0,13,23.0,7,20.0,3.823804,30.0
17,Jaguars,1519,29.0,4.440195,12.0,9,31.0,9,13.0,4.431609,13.0
19,Lions,1499,30.0,3.976075,26.0,17,16.0,8,17.0,4.055921,25.0
29,Texans,1466,31.0,4.319195,17.0,10,30.0,11,5.0,4.319987,19.0
28,Steelers,1403,32.0,3.397362,32.0,13,23.0,8,17.0,3.435079,32.0

In [24]:
total_rush_with_rank_21 = all_teams_total_rush_2021.copy()
total_rush_with_rank_21['rush_yds_rank'] = total_rush_with_rank_21['rush_yds'].rank(ascending=False, method='min')
rush_success_with_rank_21 = all_teams_rush_success_2021.copy()
rush_success_with_rank_21['rush_success_rank'] = rush_success_with_rank_21['rush_success'].rank(ascending=False, method='min')
rush_avg_with_rank_21 = all_teams_rush_avg_2021.copy()
rush_avg_with_rank_21['rush_avg_rank'] = rush_avg_with_rank_21['rush_avg'].rank(ascending=False, method='min')
rush_tds_with_rank_21 = all_teams_rush_tds_2021.copy()
rush_tds_with_rank_21['rush_tds_rank'] = rush_tds_with_rank_21['rush_tds'].rank(ascending=False, method='min')
rush_fumbles_lost_with_rank_21 = all_teams_rush_fumbles_lost_2021.copy()
rush_fumbles_lost_with_rank_21['fumbles_lost_rank'] = rush_fumbles_lost_with_rank_21['fumbles_lost'].rank(ascending=False, method='min')

In [25]:
rush_rank_21 = pd.merge(total_rush_with_rank_21[['name', 'rush_yds', 'rush_yds_rank']],
                          rush_avg_with_rank_21[['name', 'rush_avg', 'rush_avg_rank']],
                          on='name')
rush_rank_21 = pd.merge(rush_rank_21,
                          rush_tds_with_rank_21[['name', 'rush_tds', 'rush_tds_rank']],
                          on='name')
rush_rank_21 = pd.merge(rush_rank_21,
                          rush_fumbles_lost_with_rank_21[['name', 'fumbles_lost', 'fumbles_lost_rank']],
                          on='name')
rush_rank_21 = pd.merge(rush_rank_21,
                          rush_success_with_rank_21[['name', 'rush_success', 'rush_success_rank']],
                          on='name')
rush_rank_21.sort_values(by='rush_yds_rank')

,name,rush_yds,rush_yds_rank,rush_avg,rush_avg_rank,rush_tds,rush_tds_rank,fumbles_lost,fumbles_lost_rank,rush_success,rush_success_rank
13,Eagles,2810,1.0,4.983852,3.0,26,1.0,7,22.0,5.114589,2.0
30,Titans,2544,2.0,4.337042,11.0,24,2.0,11,4.0,4.438887,9.0
10,Colts,2540,3.0,5.059281,1.0,22,7.0,11,4.0,5.123599,1.0
3,Bills,2492,4.0,4.970451,4.0,23,6.0,6,28.0,5.071512,4.0
0,49ers,2491,5.0,4.194751,17.0,24,2.0,10,8.0,4.260553,19.0
25,Ravens,2479,6.0,4.680143,7.0,18,10.0,8,18.0,4.750724,6.0
5,Browns,2471,7.0,5.009967,2.0,20,9.0,8,18.0,5.083812,3.0
9,Chiefs,2382,8.0,4.726630,6.0,18,10.0,13,1.0,4.744080,7.0
22,Patriots,2242,9.0,4.192586,18.0,24,2.0,10,8.0,4.276234,18.0
11,Cowboys,2196,10.0,4.372194,10.0,16,16.0,9,12.0,4.405999,11.0
7,Cardinals,2137,11.0,4.166165,21.0,24,2.0,4,32.0,4.324699,14.0
2,Bengals,2085,12.0,3.882526,26.0,17,14.0,7,22.0,3.955998,26.0
27,Seahawks,2074,13.0,4.864106,5.0,18,10.0,6,28.0,4.971338,5.0
15,Football Team,2061,14.0,4.303989,14.0,13,22.0,9,12.0,4.333649,13.0
4,Broncos,2025,15.0,4.426517,8.0,16,16.0,9,12.0,4.474771,8.0
1,Bears,2018,16.0,4.255461,15.0,14,18.0,9,12.0,4.282953,16.0
24,Rams,2009,17.0,3.732463,28.0,12,24.0,9,12.0,3.743234,28.0
26,Saints,1991,18.0,3.849284,27.0,12,24.0,5,31.0,3.897189,27.0
20,Packers,1967,19.0,4.216724,16.0,14,18.0,7,22.0,4.253893,20.0
31,Vikings,1930,20.0,4.150103,22.0,10,29.0,6,28.0,4.183384,22.0
19,Lions,1886,21.0,4.375974,9.0,12,24.0,9,12.0,4.398585,12.0
21,Panthers,1842,22.0,4.055701,24.0,17,14.0,8,18.0,4.132348,23.0
8,Chargers,1834,23.0,4.327815,12.0,18,10.0,7,22.0,4.425783,10.0
6,Buccaneers,1829,24.0,4.173236,20.0,22,7.0,8,18.0,4.278446,17.0
17,Jaguars,1755,25.0,4.318501,13.0,13,22.0,12,2.0,4.319487,15.0
23,Raiders,1720,26.0,4.066002,23.0,14,18.0,11,4.0,4.035897,24.0
16,Giants,1688,27.0,4.055002,25.0,8,31.0,10,8.0,4.035502,25.0
18,Jets,1667,28.0,4.181280,19.0,14,18.0,7,22.0,4.245631,21.0
28,Steelers,1639,29.0,3.669147,30.0,10,29.0,10,8.0,3.675769,29.0
12,Dolphins,1568,30.0,3.506727,31.0,12,24.0,12,2.0,3.456705,31.0
14,Falcons,1451,31.0,3.679112,29.0,11,28.0,11,4.0,3.666799,30.0
29,Texans,1422,32.0,3.325111,32.0,8,31.0,7,22.0,3.306720,32.0

In [26]:
total_rush_with_rank_22 = all_teams_total_rush_2022.copy()
total_rush_with_rank_22['rush_yds_rank'] = total_rush_with_rank_22['rush_yds'].rank(ascending=False, method='min')
rush_success_with_rank_22 = all_teams_rush_success_2022.copy()
rush_success_with_rank_22['rush_success_rank'] = rush_success_with_rank_22['rush_success'].rank(ascending=False, method='min')
rush_avg_with_rank_22 = all_teams_rush_avg_2022.copy()
rush_avg_with_rank_22['rush_avg_rank'] = rush_avg_with_rank_22['rush_avg'].rank(ascending=False, method='min')
rush_tds_with_rank_22 = all_teams_rush_tds_2022.copy()
rush_tds_with_rank_22['rush_tds_rank'] = rush_tds_with_rank_22['rush_tds'].rank(ascending=False, method='min')
rush_fumbles_lost_with_rank_22 = all_teams_rush_fumbles_lost_2022.copy()
rush_fumbles_lost_with_rank_22['fumbles_lost_rank'] = rush_fumbles_lost_with_rank_22['fumbles_lost'].rank(ascending=False, method='min')

In [27]:
rush_rank_22 = pd.merge(total_rush_with_rank_22[['name', 'rush_yds', 'rush_yds_rank']],
                          rush_avg_with_rank_22[['name', 'rush_avg', 'rush_avg_rank']],
                          on='name')
rush_rank_22 = pd.merge(rush_rank_22,
                          rush_tds_with_rank_22[['name', 'rush_tds', 'rush_tds_rank']],
                          on='name')
rush_rank_22 = pd.merge(rush_rank_22,
                          rush_fumbles_lost_with_rank_22[['name', 'fumbles_lost', 'fumbles_lost_rank']],
                          on='name')
rush_rank_22 = pd.merge(rush_rank_22,
                          rush_success_with_rank_22[['name', 'rush_success', 'rush_success_rank']],
                          on='name')
rush_rank_22.sort_values(by='rush_yds_rank')

,name,rush_yds,rush_yds_rank,rush_avg,rush_avg_rank,rush_tds,rush_tds_rank,fumbles_lost,fumbles_lost_rank,rush_success,rush_success_rank
1,Bears,3014,1.0,5.427063,1.0,18,8.0,10,11.0,5.473517,1.0
13,Eagles,2925,2.0,4.548125,10.0,39,1.0,10,11.0,4.705472,8.0
25,Ravens,2875,3.0,5.196371,2.0,14,20.0,9,15.0,5.226659,2.0
16,Giants,2779,4.0,4.895365,4.0,24,3.0,10,11.0,4.996719,4.0
0,49ers,2735,5.0,4.597347,9.0,23,4.0,12,4.0,4.647262,10.0
14,Falcons,2718,6.0,4.850305,6.0,17,10.0,12,4.0,4.882905,5.0
11,Cowboys,2502,7.0,4.240610,18.0,25,2.0,5,30.0,4.367350,16.0
5,Browns,2490,8.0,4.654755,7.0,19,6.0,9,15.0,4.705622,7.0
3,Bills,2402,9.0,5.057667,3.0,17,10.0,14,2.0,5.084629,3.0
17,Jaguars,2377,10.0,4.864619,5.0,17,10.0,15,1.0,4.846520,6.0
21,Panthers,2210,11.0,4.235710,19.0,16,15.0,8,22.0,4.265508,19.0
19,Lions,2179,12.0,4.508119,12.0,23,4.0,8,22.0,4.616290,11.0
9,Chiefs,2156,13.0,4.486783,13.0,18,8.0,12,4.0,4.535922,12.0
27,Seahawks,2146,14.0,4.544404,11.0,13,21.0,12,4.0,4.517726,13.0
15,Football Team,2143,15.0,4.002327,27.0,9,29.0,7,27.0,4.012951,27.0
30,Titans,2131,16.0,4.304566,16.0,16,15.0,12,4.0,4.324849,18.0
20,Packers,2113,17.0,4.481358,14.0,12,24.0,10,11.0,4.482442,14.0
28,Steelers,2077,18.0,4.104813,25.0,16,15.0,5,30.0,4.173783,22.0
23,Raiders,2059,19.0,4.622823,8.0,12,24.0,4,32.0,4.673268,9.0
26,Saints,1982,20.0,4.169925,21.0,12,24.0,11,10.0,4.153598,24.0
4,Broncos,1935,21.0,4.418079,15.0,11,28.0,9,15.0,4.417020,15.0
7,Cardinals,1873,22.0,4.281222,17.0,15,18.0,8,22.0,4.341011,17.0
10,Colts,1866,23.0,4.155353,22.0,8,30.0,14,2.0,4.105615,25.0
2,Bengals,1822,24.0,3.808198,29.0,17,10.0,7,27.0,3.869130,29.0
22,Patriots,1812,25.0,4.181938,20.0,12,24.0,9,15.0,4.200471,20.0
12,Dolphins,1728,26.0,4.122818,23.0,13,21.0,6,29.0,4.169980,23.0
31,Vikings,1722,27.0,4.110427,24.0,19,6.0,8,22.0,4.193693,21.0
18,Jets,1686,28.0,4.061444,26.0,13,21.0,9,15.0,4.060994,26.0
24,Rams,1661,29.0,3.907344,28.0,15,18.0,8,22.0,3.944367,28.0
8,Chargers,1591,30.0,3.610929,31.0,17,10.0,9,15.0,3.661454,31.0
29,Texans,1476,31.0,3.807363,30.0,7,31.0,9,15.0,3.792657,30.0
6,Buccaneers,1360,32.0,3.271940,32.0,5,32.0,12,4.0,3.158766,32.0

In [28]:
total_rush_with_rank_23 = all_teams_total_rush_2023.copy()
total_rush_with_rank_23['rush_yds_rank'] = total_rush_with_rank_23['rush_yds'].rank(ascending=False, method='min')
rush_success_with_rank_23 = all_teams_rush_success_2023.copy()
rush_success_with_rank_23['rush_success_rank'] = rush_success_with_rank_23['rush_success'].rank(ascending=False, method='min')
rush_avg_with_rank_23 = all_teams_rush_avg_2023.copy()
rush_avg_with_rank_23['rush_avg_rank'] = rush_avg_with_rank_23['rush_avg'].rank(ascending=False, method='min')
rush_tds_with_rank_23 = all_teams_rush_tds_2023.copy()
rush_tds_with_rank_23['rush_tds_rank'] = rush_tds_with_rank_23['rush_tds'].rank(ascending=False, method='min')
rush_fumbles_lost_with_rank_23 = all_teams_rush_fumbles_lost_2023.copy()
rush_fumbles_lost_with_rank_23['fumbles_lost_rank'] = rush_fumbles_lost_with_rank_23['fumbles_lost'].rank(ascending=False, method='min')

In [29]:
rush_rank_23 = pd.merge(total_rush_with_rank_23[['name', 'rush_yds', 'rush_yds_rank']],
                          rush_avg_with_rank_23[['name', 'rush_avg', 'rush_avg_rank']],
                          on='name')
rush_rank_23 = pd.merge(rush_rank_23,
                          rush_tds_with_rank_23[['name', 'rush_tds', 'rush_tds_rank']],
                          on='name')
rush_rank_23 = pd.merge(rush_rank_23,
                          rush_fumbles_lost_with_rank_23[['name', 'fumbles_lost', 'fumbles_lost_rank']],
                          on='name')
rush_rank_23 = pd.merge(rush_rank_23,
                          rush_success_with_rank_23[['name', 'rush_success', 'rush_success_rank']],
                          on='name')
rush_rank_23.sort_values(by='rush_yds_rank')

,name,rush_yds,rush_yds_rank,rush_avg,rush_avg_rank,rush_tds,rush_tds_rank,fumbles_lost,fumbles_lost_rank,rush_success,rush_success_rank
25,Ravens,2971,1.0,4.898824,3.0,28,3.0,14,4.0,4.974038,4.0
19,Lions,2686,2.0,4.619163,5.0,34,1.0,12,9.0,4.777945,5.0
0,49ers,2655,3.0,4.855727,4.0,32,2.0,6,25.0,5.043883,3.0
3,Bills,2573,4.0,4.317945,8.0,25,5.0,10,14.0,4.401976,8.0
1,Bears,2399,5.0,4.421257,7.0,16,11.0,10,14.0,4.463493,7.0
12,Dolphins,2384,6.0,4.979173,1.0,27,4.0,10,14.0,5.096392,1.0
7,Cardinals,2365,7.0,4.960047,2.0,17,9.0,6,25.0,5.044784,2.0
13,Eagles,2232,8.0,4.098325,17.0,22,6.0,12,9.0,4.147235,16.0
20,Packers,2184,9.0,4.274969,10.0,13,18.0,7,22.0,4.320509,10.0
9,Chiefs,2166,10.0,4.220416,11.0,12,20.0,13,6.0,4.188809,14.0
14,Falcons,2159,11.0,4.121812,15.0,14,16.0,11,12.0,4.139722,18.0
28,Steelers,2116,12.0,4.102586,16.0,16,11.0,8,19.0,4.150601,15.0
24,Rams,2113,13.0,4.304191,9.0,18,8.0,5,30.0,4.401474,9.0
5,Browns,2073,14.0,3.749948,26.0,16,11.0,14,4.0,3.759481,25.0
10,Colts,2059,15.0,4.173752,12.0,19,7.0,12,9.0,4.230381,11.0
11,Cowboys,2043,16.0,4.140946,14.0,15,15.0,6,25.0,4.203803,13.0
16,Giants,1874,17.0,4.090266,19.0,10,26.0,7,22.0,4.126504,19.0
30,Titans,1846,18.0,4.093005,18.0,16,11.0,9,18.0,4.144715,17.0
4,Broncos,1810,19.0,4.063078,20.0,8,28.0,13,6.0,4.008159,20.0
21,Panthers,1769,20.0,3.919730,22.0,7,30.0,10,14.0,3.902532,23.0
29,Texans,1761,21.0,3.641562,30.0,11,22.0,6,25.0,3.682345,27.0
26,Saints,1742,22.0,3.607301,31.0,13,18.0,7,22.0,3.632457,31.0
6,Buccaneers,1717,23.0,3.692139,27.0,8,28.0,8,19.0,3.661840,28.0
18,Jets,1647,24.0,4.061214,21.0,7,30.0,18,1.0,3.908165,22.0
17,Jaguars,1646,25.0,3.595119,32.0,17,9.0,16,2.0,3.550933,32.0
8,Chargers,1642,26.0,3.685065,29.0,11,22.0,13,6.0,3.640694,30.0
22,Patriots,1627,27.0,3.855530,24.0,9,27.0,8,19.0,3.872227,24.0
15,Football Team,1592,28.0,4.467942,6.0,14,16.0,11,12.0,4.467018,6.0
27,Seahawks,1580,29.0,4.153156,13.0,11,22.0,5,30.0,4.209320,12.0
31,Vikings,1553,30.0,3.801479,25.0,7,30.0,15,3.0,3.650773,29.0
23,Raiders,1542,31.0,3.687631,28.0,11,22.0,6,25.0,3.714777,26.0
2,Bengals,1527,32.0,3.890168,23.0,12,20.0,2,32.0,3.976095,21.0

In [36]:
team_rushing_rankings = pd.merge(rush_rank_19[['name', 'rush_yds_rank', 'rush_success_rank']],
                                  rush_rank_20[['name', 'rush_yds_rank', 'rush_success_rank']],
                                  on='name',
                                  suffixes=('_2019', '_2020'))
team_rushing_rankings = pd.merge(team_rushing_rankings,
                                  rush_rank_21[['name', 'rush_yds_rank', 'rush_success_rank']],
                                  on='name',
                                  suffixes=('', '_2021'))
team_rushing_rankings = pd.merge(team_rushing_rankings,
                                  rush_rank_22[['name', 'rush_yds_rank', 'rush_success_rank']],
                                  on='name',
                                  suffixes=('', '_2022'))
team_rushing_rankings = pd.merge(team_rushing_rankings,
                                  rush_rank_23[['name', 'rush_yds_rank', 'rush_success_rank']],
                                  on='name',
                                  suffixes=('', '_2023'))
team_rushing_rankings

,name,rush_yds_rank_2019,rush_success_rank_2019,rush_yds_rank_2020,rush_success_rank_2020,rush_yds_rank,rush_success_rank,rush_yds_rank_2022,rush_success_rank_2022,rush_yds_rank_2023,rush_success_rank_2023
0,49ers,2.0,4.0,18.0,16.0,5.0,19.0,5.0,10.0,3.0,3.0
1,Bears,27.0,30.0,24.0,26.0,16.0,16.0,1.0,1.0,5.0,7.0
2,Bengals,25.0,28.0,27.0,28.0,12.0,26.0,24.0,29.0,32.0,21.0
3,Bills,7.0,11.0,15.0,20.0,4.0,4.0,9.0,3.0,4.0,8.0
4,Broncos,21.0,21.0,16.0,15.0,15.0,8.0,21.0,15.0,19.0,20.0
5,Browns,14.0,3.0,3.0,7.0,7.0,3.0,8.0,7.0,14.0,25.0
6,Buccaneers,24.0,24.0,14.0,24.0,24.0,17.0,32.0,32.0,23.0,28.0
7,Cardinals,11.0,5.0,9.0,9.0,11.0,14.0,22.0,17.0,7.0,2.0
8,Chargers,28.0,25.0,20.0,31.0,23.0,10.0,30.0,31.0,26.0,30.0
9,Chiefs,13.0,13.0,11.0,12.0,8.0,7.0,13.0,12.0,10.0,14.0
10,Colts,9.0,14.0,10.0,11.0,3.0,1.0,23.0,25.0,15.0,11.0
11,Cowboys,8.0,8.0,19.0,22.0,10.0,11.0,7.0,16.0,16.0,13.0
12,Dolphins,32.0,32.0,25.0,29.0,30.0,31.0,26.0,23.0,6.0,1.0
13,Eagles,10.0,18.0,13.0,2.0,1.0,2.0,2.0,8.0,8.0,16.0
14,Falcons,30.0,27.0,28.0,30.0,31.0,30.0,6.0,5.0,11.0,18.0
15,Football Team,23.0,17.0,23.0,27.0,14.0,13.0,15.0,27.0,28.0,6.0
16,Giants,20.0,10.0,21.0,14.0,27.0,25.0,4.0,4.0,17.0,19.0
17,Jaguars,19.0,20.0,29.0,13.0,25.0,15.0,10.0,6.0,25.0,32.0
18,Jets,31.0,31.0,26.0,21.0,28.0,21.0,28.0,26.0,24.0,22.0
19,Lions,22.0,22.0,30.0,25.0,21.0,12.0,12.0,11.0,2.0,5.0
20,Packers,12.0,16.0,5.0,8.0,19.0,20.0,17.0,14.0,9.0,10.0
21,Panthers,17.0,6.0,22.0,17.0,22.0,23.0,11.0,19.0,20.0,23.0
22,Patriots,18.0,23.0,6.0,6.0,9.0,18.0,25.0,20.0,27.0,24.0
23,Raiders,15.0,15.0,17.0,23.0,26.0,24.0,19.0,9.0,31.0,26.0
24,Rams,26.0,26.0,8.0,18.0,17.0,28.0,29.0,28.0,13.0,9.0
25,Ravens,1.0,1.0,1.0,1.0,6.0,6.0,3.0,2.0,1.0,4.0
26,Saints,16.0,9.0,4.0,10.0,18.0,27.0,20.0,24.0,22.0,31.0
27,Seahawks,4.0,12.0,12.0,4.0,13.0,5.0,14.0,13.0,29.0,12.0
28,Steelers,29.0,29.0,32.0,32.0,29.0,29.0,18.0,22.0,12.0,15.0
29,Texans,6.0,7.0,31.0,19.0,32.0,32.0,31.0,30.0,21.0,27.0
30,Titans,3.0,2.0,2.0,3.0,2.0,9.0,16.0,18.0,18.0,17.0
31,Vikings,5.0,19.0,7.0,5.0,20.0,22.0,27.0,21.0,30.0,29.0